apiVersion: apps/v1
kind: Deployment
metadata:
  name: b17
spec:
  replicas: 2
  selector:
    matchLabels:
      app: b17

  template:
    metadata:
      labels:
        app: b17

    spec:
      containers:
        - name: b17-container
          image: 078601217097.dkr.ecr.ap-south-1.amazonaws.com/b17:latest
          ports:
            - containerPort: 80
