name:  Myfirstworkflow

on: 
    push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: putting code on runner
              run:  git clone https://github.com/shindesusmita10-spec/Github-Actions1.git

            - name: checking the code
              run: |
                ls -la
                chmod +x .github/workflows/new.sh
                .github/workflows/./new.sh
    

            